server:
  port: 5432

log: !Kafka
  bootstrapServers: !Env KAFKA_BOOTSTRAP_SERVERS
  txTopic: !Env XTDB_TX_TOPIC
  filesTopic: !Env XTDB_FILES_TOPIC
  
storage: !Local
  path: "/var/lib/xtdb/buffers"

healthz:
  port: 8080

modules: 
- !HttpServer
  port: 3000


