# Check https://circleci.com/docs/2.0/language-clojure/ for more details
version: 2.1

executors:
  clojure:
    working_directory: ~/core2
    docker:
      - image: clojure:openjdk-17-tools-deps

parameters:
  run-slt:
    type: boolean
    default: false

jobs:
  setup:
    executor: clojure

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: apt-get update && apt-get install -y curl

      - run: 'md5sum deps.edn */deps.edn modules/*/deps.edn > .circleci-cache-key'

      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum ".circleci-cache-key" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-

      - run: 'clojure -Srepro -X:deps prep'

      # https://clojure.atlassian.net/browse/TDEPS-153
      # can remove `-Sthreads 1` when the Docker image updates to 1.11.0.1100 or later.
      - run: 'clojure -P -Sthreads 1'

      - run: 'mkdir ~/slt-results'


      - persist_to_workspace:
          root: ~/
          paths:
            - .m2
            - .gitlibs
            - core2
            - slt-results

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: v4-dependencies-{{ checksum ".circleci-cache-key" }}

  #disabled
  third-party-notices:
    executor: clojure

    steps:
      - attach_workspace:
          at: ~/

      - run: apt-get update && apt-get install -y curl maven libxml2-utils

      - run: curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install && chmod +x install && ./install

      - run: ./bin/detect-and-create-third-party-notices.sh

      - run: bb ./bin/detect_eclipse_public_license.clj

  test:
    executor: clojure

    steps:
      - attach_workspace:
          at: ~/

      - run: apt-get update && apt-get install -y curl
      - run: 'clojure -Srepro -X:xtdb:4gb:test'

  integration-test:
    executor: clojure

    steps:
      - attach_workspace:
          at: ~/

      - run: apt-get update && apt-get install -y curl
      # TODO should test the other modules too
      - run: 'clojure -Srepro -X:xtdb:4gb:integration-test'

  slt-test:
    executor: clojure
    resource_class: medium

    steps:
      - attach_workspace:
          at: ~/

      - run: 'clojure -Srepro -M:xtdb:4gb:slt-test'

  slt-test-2:
    executor: clojure
    resource_class: medium

    steps:
      - attach_workspace:
          at: ~/

      - run: 'clojure -Srepro -M:xtdb:4gb:slt-test-2'

  slt-test-dirs:
    executor: clojure
    resource_class: medium+
    parameters:
      dirs:
        type: string

    steps:
      - attach_workspace:
          at: ~/

      - run: 'clojure -Srepro -M:xtdb:6gb:slt-test-dirs << parameters.dirs >>'

      - persist_to_workspace:
          root: ~/
          paths: slt-results

  store-test-results:

    executor: clojure
    resource_class: medium

    steps:
      - attach_workspace:
          at: ~/

      - run: 'clojure -Srepro -X:slt-print-results'

workflows:
  build:
    when:
      not: << pipeline.parameters.run-slt >>
    jobs:
      - setup
      # - third-party-notices:
      #     requires:
      #       - setup
      - test:
          requires:
            - setup
      - integration-test:
          requires:
            - setup
      - slt-test:
          requires:
           - setup
      - slt-test-2:
          requires:
            - setup

  slt-nightly:
    when: << pipeline.parameters.run-slt >>
    jobs:
      - setup
      - slt-test-dirs:
          requires:
            - setup
          matrix:
            parameters:
              dirs:
                - "src/test/resources/xtdb/sql/logic_test/sqlite_test/random/expr/"
                - "src/test/resources/xtdb/sql/logic_test/sqlite_test/random/aggregates/"
                - "src/test/resources/xtdb/sql/logic_test/sqlite_test/random/groupby/"
                - "src/test/resources/xtdb/sql/logic_test/sqlite_test/random/select/"
                - "src/test/resources/xtdb/sql/logic_test/sqlite_test/index/between/"
                - "src/test/resources/xtdb/sql/logic_test/sqlite_test/index/commute/"
                - "src/test/resources/xtdb/sql/logic_test/sqlite_test/index/orderby/"
                - "src/test/resources/xtdb/sql/logic_test/sqlite_test/index/orderby_nosort/"
                - "src/test/resources/xtdb/sql/logic_test/sqlite_test/index/in/"
                - "src/test/resources/xtdb/sql/logic_test/sqlite_test/index/random/"
                  #  - "src/test/resources/xtdb/sql/logic_test/sqlite_test/index/delete/"
                  #  - "src/test/resources/xtdb/sql/logic_test/sqlite_test/index/view/"
      - store-test-results:
          requires:
            - slt-test-dirs
            - setup
