[versions]
antlr="4.13.2"
arrow="18.1.0"
arrow-adbc="0.15.0"
clojure="1.12.0"
netty="4.1.117.Final"
reitit="0.5.15"
muuntaja="0.6.8"
testcontainers="1.20.3"
micrometer="1.14.1"
transit="1.0.329"

[libraries]
arrow-algorithm={ group="org.apache.arrow", name="arrow-algorithm", version.ref="arrow" }
arrow-memory-netty={ group="org.apache.arrow", name="arrow-memory-netty", version.ref="arrow" }
arrow-compression={ group="org.apache.arrow", name="arrow-compression", version.ref="arrow" }
arrow-vector={ group="org.apache.arrow", name="arrow-vector", version.ref="arrow" }
arrow-adbc={ group="org.apache.arrow.adbc", name="adbc-core", version.ref="arrow-adbc" }
arrow-adbc-fsql={ group="org.apache.arrow.adbc", name="adbc-driver-flight-sql", version.ref="arrow-adbc" }
netty-common={ group="io.netty", name="netty-common", version.ref="netty" }

roaring-bitmap={ group="org.roaringbitmap", name="RoaringBitmap", version="1.3.0" }
hppc={ group="com.carrotsearch", name="hppc", version="0.9.1" }
caffeine={ group="com.github.ben-manes.caffeine", name="caffeine", version="3.1.8" }
commons-codec={ group="commons-codec", name="commons-codec", version="1.15" }

antlr={ group="org.antlr", name="antlr4", version.ref="antlr" }
antlr-runtime={ group="org.antlr", name="antlr4-runtime", version.ref="antlr" }

clojure={ group="org.clojure", name="clojure", version.ref="clojure" }
clojure-test-check={ group="org.clojure", name="test.check", version="1.1.1" }
clojure-tools-logging={ group="org.clojure", name="tools.logging", version="1.2.4" }
clojure-spec={ group="org.clojure", name="spec.alpha", version="0.3.218" }
clojure-data-json={ group="org.clojure", name="data.json", version="2.4.0" }
clojure-data-csv={ group="org.clojure", name="data.csv", version="1.0.1" }
clojure-tools-cli={ group="org.clojure", name="tools.cli", version="1.0.206" }
clj-yaml={ group="clj-commons", name="clj-yaml", version="1.0.27" }
transit-clj={ group="com.cognitect", name="transit-clj", version.ref="transit" }
transit-java={ group="com.cognitect", name="transit-java", version.ref="transit" }
next-jdbc={ group="com.github.seancorfield", name="next.jdbc", version="1.3.955" }
honeysql={ group="com.github.seancorfield", name="honeysql", version="2.6.1203" }
integrant={ group="integrant", name="integrant", version="0.13.1" }
sci={ group="org.babashka", name="sci", version="0.6.37" }
buddy-hashers={ group="buddy", name="buddy-hashers", version="2.0.167" }

pgjdbc={ group="org.postgresql", name="postgresql", version="42.7.3" }

kotlinx-serialization-json={ group="org.jetbrains.kotlinx", name="kotlinx-serialization-json", version="1.8.0" }
mockk={ group="io.mockk", name="mockk", version="1.13.9" }
kaml={ group="com.charleskorn.kaml", name="kaml", version="0.56.0" }

jsonista={ group="metosin", name="jsonista", version="0.3.3" }
muuntaja={ group="metosin", name="muuntaja", version.ref="muuntaja" }
reitit-core={ group="metosin", name="reitit-core", version.ref="reitit" }
reitit-interceptors={ group="metosin", name="reitit-interceptors", version.ref="reitit" }
reitit-ring={ group="metosin", name="reitit-ring", version.ref="reitit" }
reitit-http={ group="metosin", name="reitit-http", version.ref="reitit" }
reitit-sieppari={ group="metosin", name="reitit-sieppari", version.ref="reitit" }
reitit-swagger={ group="metosin", name="reitit-swagger", version.ref="reitit" }
reitit-spec={ group="metosin", name="reitit-spec", version.ref="reitit" }

ring-core={ group="ring", name="ring-core", version="1.10.0" }
ring-jetty9-adapter={ group="info.sunng", name="ring-jetty9-adapter", version="0.22.4" }
jetty-alpn-server={ group="org.eclipse.jetty", name="jetty-alpn-server", version="10.0.15" }

testcontainers={ group="org.testcontainers", name="testcontainers", version.ref="testcontainers" }
testcontainers-kafka={ group="org.testcontainers", name="kafka", version.ref="testcontainers" }
testcontainers-minio={ group="org.testcontainers", name="minio", version.ref="testcontainers" }

micrometer-core={ group="io.micrometer", name="micrometer-core", version.ref="micrometer" }
micrometer-registry-prometheus={ group="io.micrometer", name="micrometer-registry-prometheus", version.ref="micrometer" }
micrometer-registry-cloudwatch2={ group="io.micrometer", name="micrometer-registry-cloudwatch2", version.ref="micrometer" }
micrometer-registry-azuremonitor={ group="io.micrometer", name="micrometer-registry-azure-monitor", version.ref="micrometer" }
