[versions]
arrow="17.0.0"
arrow-adbc="0.14.0"
clojure="1.12.0"
netty="4.1.110.Final"
reitit="0.5.15"
muuntaja="0.6.8"
testcontainers="1.20.3"

[libraries]
arrow-algorithm={ group="org.apache.arrow", name="arrow-algorithm", version.ref="arrow" }
arrow-memory-netty={ group="org.apache.arrow", name="arrow-memory-netty", version.ref="arrow" }
arrow-compression={ group="org.apache.arrow", name="arrow-compression", version.ref="arrow" }
arrow-vector={ group="org.apache.arrow", name="arrow-vector", version.ref="arrow" }
arrow-adbc={ group="org.apache.arrow.adbc", name="adbc-core", version.ref="arrow-adbc" }
arrow-adbc-fsql={ group="org.apache.arrow.adbc", name="adbc-driver-flight-sql", version.ref="arrow-adbc" }
netty-common={ group="io.netty", name="netty-common", version.ref="netty" }

clojure={ group="org.clojure", name="clojure", version.ref="clojure" }
clojure-tools-logging={ group="org.clojure", name="tools.logging", version="1.2.4" }
clojure-spec={ group="org.clojure", name="spec.alpha", version="0.3.218" }
clojure-data-json={ group="org.clojure", name="data.json", version="2.4.0" }
clojure-data-csv={ group="org.clojure", name="data.csv", version="1.0.1" }
clojure-tools-cli={ group="org.clojure", name="tools.cli", version="1.0.206" }
transit-clj={ group="com.cognitect", name="transit-clj", version="1.0.329" }
next-jdbc={ group="com.github.seancorfield", name="next.jdbc", version="1.3.955" }
honeysql={ group="com.github.seancorfield", name="honeysql", version="2.6.1203" }

muuntaja={ group="metosin", name="muuntaja", version.ref="muuntaja" }
reitit-core={ group="metosin", name="reitit-core", version.ref="reitit" }
reitit-interceptors={ group="metosin", name="reitit-interceptors", version.ref="reitit" }
reitit-ring={ group="metosin", name="reitit-ring", version.ref="reitit" }
reitit-http={ group="metosin", name="reitit-http", version.ref="reitit" }
reitit-sieppari={ group="metosin", name="reitit-sieppari", version.ref="reitit" }
reitit-swagger={ group="metosin", name="reitit-swagger", version.ref="reitit" }
reitit-spec={ group="metosin", name="reitit-spec", version.ref="reitit" }

ring-core={ group="ring", name="ring-core", version="1.10.0" }
ring-jetty9-adapter={ group="info.sunng", name="ring-jetty9-adapter", version="0.22.4" }
jetty-alpn-server={ group="org.eclipse.jetty", name="jetty-alpn-server", version="10.0.15" }

testcontainers={ group="org.testcontainers", name="testcontainers", version.ref="testcontainers" }
testcontainers-kafka={ group="org.testcontainers", name="kafka", version.ref="testcontainers" }
testcontainers-minio={ group="org.testcontainers", name="minio", version.ref="testcontainers" }
