# Use any available port for PGWire Server.
server: 
  port: 0

# CONFIG FOR RUNNING WITH AZURE INFRA
txLog: !Kafka
  bootstrapServers: !Env KAFKA_BOOTSTRAP_SERVERS
  txTopic: !Env XTDB_TX_TOPIC
  filesTopic: !Env XTDB_FILES_TOPIC


# txLog: !Local
#   path: !Env XTDB_LOCAL_LOG_PATH

storage: !Remote
  objectStore: !Azure
    storageAccount: !Env XTDB_AZURE_STORAGE_ACCOUNT
    container: !Env XTDB_AZURE_STORAGE_CONTAINER
    prefix: "xtdb-object-store"
    userManagedIdentityClientId: !Env XTDB_AZURE_USER_MANAGED_IDENTITY_CLIENT_ID
  localDiskCache: !Env XTDB_LOCAL_DISK_CACHE
  maxDiskCachePercentage: 75

modules:
  - !AzureMonitor
    instrumentationKey: !Env XTDB_AZURE_INSTRUMENTATION_KEY
