healthz:
  port: !Env XTDB_HEALTHZ_PORT

# CONFIG FOR RUNNING WITH AZURE INFRA
log: !Kafka
  bootstrapServers: !Env KAFKA_BOOTSTRAP_SERVERS
  txTopic: !Env XTDB_TX_TOPIC
  filesTopic: !Env XTDB_FILES_TOPIC


# log: !Local
#   path: !Env XTDB_LOCAL_LOG_PATH

storage: !Remote
  objectStore: !Azure
    storageAccount: !Env XTDB_AZURE_STORAGE_ACCOUNT
    container: !Env XTDB_AZURE_STORAGE_CONTAINER
    prefix: "xtdb-object-store"
    userManagedIdentityClientId: !Env XTDB_AZURE_USER_MANAGED_IDENTITY_CLIENT_ID
  localDiskCache: !Env XTDB_LOCAL_DISK_CACHE
  maxDiskCachePercentage: 75

modules:
  - !AzureMonitor
    connectionString: !Env XTDB_AZURE_APP_INSIGHTS_CONNECTION_STRING
