apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "xtdb-pvc-local-cache-lp"
  namespace: "cloud-benchmark"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "50Gi"
  storageClassName: "managed-csi"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "xtdb-pvc-local-cache-1"
  namespace: "cloud-benchmark"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "50Gi"
  storageClassName: "managed-csi"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "xtdb-pvc-local-cache-2"
  namespace: "cloud-benchmark"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "50Gi"
  storageClassName: "managed-csi"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "xtdb-pvc-local-cache-3"
  namespace: "cloud-benchmark"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "50Gi"
  storageClassName: "managed-csi"
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "xtdb-env-config"
  namespace: "cloud-benchmark"
data:
  CLOUD_PLATFORM_NAME: "Azure"
  XTDB_AZURE_USER_MANAGED_IDENTITY_CLIENT_ID: "7992730c-e4a3-4b37-84ae-bd802bb58524"
  XTDB_AZURE_STORAGE_ACCOUNT: "xtdbazurebenchmark"
  XTDB_AZURE_STORAGE_CONTAINER: "xtdbazurebenchmarkcontainer"
  XTDB_AZURE_SERVICE_BUS_NAMESPACE: "cloud-benchmark-eventbus"
  XTDB_AZURE_SERVICE_BUS_TOPIC_NAME: "cloud-benchmark-servicebus-topic"
  XTDB_AZURE_APP_INSIGHTS_CONNECTION_STRING: ""
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service.cloud-benchmark.svc.cluster.local:9092"
  XTDB_TX_TOPIC: "xtdb-tx-topic"
  XTDB_FILES_TOPIC: "xtdb-files-topic"
  AUCTIONMARK_DURATION: "PT24H"
  AUCTIONMARK_SCALE_FACTOR: "0.1"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "xtdb-multi-node-auctionmark"
  namespace: "cloud-benchmark"
  labels:
    app: "xtdb-multi-node-auctionmark"
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: "xtdb-multi-node-auctionmark"
        azure.workload.identity/use: "true" 
    spec:
      nodeSelector:
        nodepool: "benchmark"
      serviceAccountName: "xtdb-service-account"
      restartPolicy: "Never"
      volumes:
        - name: "xtdb-pvc-local-cache-lp-vol"
          persistentVolumeClaim:
            claimName: "xtdb-pvc-local-cache-lp"
        - name: "xtdb-pvc-local-cache-1-vol"
          persistentVolumeClaim:
            claimName: "xtdb-pvc-local-cache-1"
        - name: "xtdb-pvc-local-cache-2-vol"
          persistentVolumeClaim:
            claimName: "xtdb-pvc-local-cache-2"
        - name: "xtdb-pvc-local-cache-3-vol"
          persistentVolumeClaim:
            claimName: "xtdb-pvc-local-cache-3"
      initContainers:
      - name: wait-for-kafka
        image: busybox
        command: ['sh', '-c', 'until nc -z kafka-service.cloud-benchmark.svc.cluster.local 9092; do echo waiting for kafka; sleep 5; done;']
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "256Mi"
      - name: load-phase
        image: cloudbenchmarkregistry.azurecr.io/xtdb-azure-bench:latest
        volumeMounts:
        - mountPath: /var/lib/xtdb/buffers
          name: xtdb-pvc-local-cache-lp-vol
        resources:
          requests:
            memory: "6244Mi"
          limits:
            memory: "6244Mi"
        envFrom:
        - configMapRef:
            name: xtdb-env-config
        env:
        - name: XTDB_LOCAL_DISK_CACHE
          value: "/var/lib/xtdb/buffers/disk-cache-lp"
        - name: AUCTIONMARK_LOAD_PHASE_ONLY
          value: "True"
        - name: XTDB_NODE_ID
          value: "bench-load-phase"
        - name: XTDB_HEALTHZ_PORT
          value: "8080"
        ports:
          - name: metrics 
            containerPort: 8080
            hostPort: 8080
      containers:
      - name: xtdb-azure-bench-1
        image: cloudbenchmarkregistry.azurecr.io/xtdb-azure-bench:latest
        volumeMounts:
        - mountPath: /var/lib/xtdb/buffers
          name: xtdb-pvc-local-cache-1-vol
        resources:
          requests:
            memory: "6244Mi"
          limits:
            memory: "6244Mi"
        envFrom:
        - configMapRef:
            name: xtdb-env-config
        env:
        - name: XTDB_LOCAL_DISK_CACHE
          value: "/var/lib/xtdb/buffers/disk-cache-1"
        - name: AUCTIONMARK_LOAD_PHASE
          value: "False"
        - name: XTDB_NODE_ID
          value: "bench-node-1"
        - name: XTDB_HEALTHZ_PORT
          value: "8081"
        ports: 
        - name: metrics 
          containerPort: 8081
          hostPort: 8081
      - name: xtdb-azure-bench-2
        image: cloudbenchmarkregistry.azurecr.io/xtdb-azure-bench:latest
        volumeMounts:
        - mountPath: /var/lib/xtdb/buffers
          name: xtdb-pvc-local-cache-2-vol
        resources:
          requests:
            memory: "6244Mi"
          limits:
            memory: "6244Mi"
        envFrom:
        - configMapRef:
            name: xtdb-env-config
        env:
        - name: XTDB_LOCAL_DISK_CACHE
          value: "/var/lib/xtdb/buffers/disk-cache-2"
        - name: AUCTIONMARK_LOAD_PHASE
          value: "False"
        - name: XTDB_NODE_ID
          value: "bench-node-2"
        - name: XTDB_HEALTHZ_PORT
          value: "8082"
        ports: 
        - name: metrics 
          containerPort: 8082
          hostPort: 8082
      - name: xtdb-azure-bench-3
        image: cloudbenchmarkregistry.azurecr.io/xtdb-azure-bench:latest
        volumeMounts:
        - mountPath: /var/lib/xtdb/buffers
          name: xtdb-pvc-local-cache-3-vol
        resources:
          requests:
            memory: "6244Mi"
          limits:
            memory: "6244Mi"
        envFrom:
        - configMapRef:
            name: xtdb-env-config
        env:
        - name: XTDB_LOCAL_DISK_CACHE
          value: "/var/lib/xtdb/buffers/disk-cache-3"
        - name: AUCTIONMARK_LOAD_PHASE
          value: "False"
        - name: XTDB_NODE_ID
          value: "bench-node-3"
        - name: XTDB_HEALTHZ_PORT
          value: "8083"
        ports: 
        - name: metrics 
          containerPort: 8083
          hostPort: 8083
