server:
  port: 5432

log: !Local
  path: !Env XTDB_GCP_LOCAL_LOG_PATH

storage: !Remote
  objectStore: !GoogleCloud
    projectId: !Env XTDB_GCP_PROJECT_ID
    bucket: !Env XTDB_GCP_BUCKET
    prefix: !Env XTDB_GCP_BUCKET_PREFIX
  localDiskCache: !Env XTDB_GCP_LOCAL_DISK_CACHE_PATH
