{{- $usermanagedidentity := .Values.xtdbConfig.userManagedIdentityClientId | required "xtdbConfig.userManagedIdentityClientId is required." -}}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "{{ $usermanagedidentity }}"
  name: "xtdb-service-account"
  namespace: {{ .Release.Namespace }}
