txLog: !Kafka
  bootstrapServers: !Env KAFKA_BOOTSTRAP_SERVERS
  txTopic: !Env XTDB_TX_TOPIC
  filesTopic: !Env XTDB_FILES_TOPIC
  propertiesMap:
    sasl.mechanism: !Env KAFKA_SASL_MECHANISM
    security.protocol: !Env KAFKA_SECURITY_PROTOCOL
    sasl.jaas.config: !Env KAFKA_SASL_JAAS_CONFIG

storage: !Remote
  objectStore: !Azure
    storageAccountEndpoint: !Env XTDB_AZURE_STORAGE_ACCOUNT_ENDPOINT
    container: !Env XTDB_AZURE_STORAGE_CONTAINER
    prefix: "xtdb-object-store"
    userManagedIdentityClientId: !Env XTDB_AZURE_USER_MANAGED_IDENTITY_CLIENT_ID
  localDiskCache: !Env XTDB_LOCAL_DISK_CACHE
  
metrics: !Prometheus
  port: 8080

modules: 
- !HttpServer
  port: 3000
