name: XTDB CI
run-name: XTDB CI

on:
  push:
    branches-ignore:
      - docs-live

jobs:
  gradle-test:
    name: Gradle Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Test
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          check_name: JUnit Test Report
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Post Slack Notification (On Fail)
        if: failure() && github.repository == 'xtdb/xtdb' && github.ref == 'refs/heads/main'
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "*{workflow}* has {status_message}:"
          message_format: "{emoji} `gradle-test` job has {status_message} in *{workflow}*"
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  lang-test:
    name: Non-JVM language tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build XTDB shadowJar
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: :docker:standalone:shadowJar
      - name: XTDB service
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          services: "xtdb"
          cwd: "lang"
      - name: JS test
        working-directory: "lang"
        run: |
          docker compose run js

      - name: Python test
        working-directory: "lang"
        run: |
          docker compose run python

      - name: Elixir test
        working-directory: "lang"
        run: |
          docker compose run elixir

      - name: Post Slack Notification (On Fail)
        if: failure() && github.repository == 'xtdb/xtdb' && github.ref == 'refs/heads/main'
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "*{workflow}* has {status_message}:"
          message_format: "{emoji} `lang-test` job has {status_message} in *{workflow}*"
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Integration Test
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: integration-test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          check_name: JUnit Integration Test Report
          report_paths: '**/build/test-results/integration-test/TEST-*.xml'
      - name: Post Slack Notification (On Fail)
        if: failure() && github.repository == 'xtdb/xtdb' && github.ref == 'refs/heads/main'
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "*{workflow}* has {status_message}:"
          message_format: "{emoji} `integration-test` job has {status_message} in *{workflow}*"
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  slt-1:
    name: SLT 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: SLT 1
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: slt-test

  slt-2:
    name: SLT 2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: SLT 2
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: slt-test-2
