name: XTDB Edge

on:
  workflow_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  helm:
    uses: ./.github/workflows/helm.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      appVersion: edge
